name: GHA from scratch
on: [workflow_dispatch]


jobs:
   print:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v3
          - name: print something
            run: echo hello world

        
   print2:
      runs-on: ubuntu-latest
      needs: print
      steps:
            
          - uses: actions/checkout@v3
          - name: printing second statement
            run: echo abc
            
