name: GHA from scratch
on:
   workflow_dispatch:
      inputs :
         name :
            description: 'name of the person'
            required: true #a required field is added when it asks for name
            default: 'Madhurya'# shows default name as Madhurya if u dont provide the name
         country:
            description: 'name of the country'
            required: false
jobs:
   print:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v3
          - name: print something
            run: echo hello world

        
   print2:
      runs-on: ubuntu-latest
      needs: print
      steps:
            
          # - uses: actions/checkout@v3 
          - name: printing second statement
            run: echo abc

   greetuser:     
         runs-on: ubuntu-latest
         steps:
         
             - name: greet the user
               run: echo "Hi ${{github.event.inputs.name}}"
                    echo "- in ${{github.event.inputs.country}}"
         
            
